# Generated by Django 4.2.1 on 2023-05-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('price', models.PositiveSmallIntegerField()),
                ('units', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
    ]
